export default PromptList = [
  "What makes fake news so appealing?", 
  "What movie are you most excited about this year?",
  "Talk about an experience you've had with VR.",
  "What do you think VR holds for the future?",
  "Talk about your favorite musician",
  "How do you think Donald Trump would handle a scandal like Watergate?",
  "How would life be different if Hillary Clinton won the US presidential election?",
  "How would life be different if Bernie Sanders won the US presidential election?",
  "What are your opinions on the legalization of marijuana?" ,
  "What is one of the biggest challenges in your life?" ,
  "What is your favorite book?" ,
  "How would you define success? Is success just a function of wealth or is it more than that?" ,
  "What do you think about the rapid growth of Artificial Intelligence? Are you worried AI will take over the world?" ,
  "Do you think the United Nations is successful? If so - where does it succeed? Otherwise why not?", 
  "What do you think differentiates people who are \"successful\" versus those who are not?", 
  "Why do you think there are so many different religions in the history of humanity?" ,
  "What is the best TV show currently airing?" ,
  "What is the best TV show of all time?", 
  "Where was your favorite vacation at? What did you like about it?" ,
  "What do you think of Trump's Healthcare Plan?" ,
  "What would be the pros and cons of the US lowering the legal drinking age from 21 to 18?" ,
  "What's your number one goal in life?" ,
  "What do you think about the CIA hacking documents leak? Do you think WikiLeaks was justified to release these documents?" ,
  "What are your opinions on genetically modified organisms?" ,
  "What do you think of Trump's attempted travel ban?" ,
  "What do you do in your freetime?" ,
  "What is your favorite genre of music?" ,
  "What was the last song you listened to?" ,
  "What do you think of single-sex schools? Do you think they are beneficial or harmful to a student's education?" ,
  "What do you think of human cloning?" ,
  "How can we fix global warming?" ,
  "What are your thoughts on assisted suicide?" ,
  "What do you think of Betsy DeVos as US Secretary of Education?" ,
  "What is your opinion on Capitalism?" ,
  "What are your thoughts on the 2016 US Election?" ,
  "Why does our society like to watch sports?", 
  "Why do you think the US considers death penalty appropriate for some crimes and not others?" ,
  "Who is your favorite comedian?" ,
  "What do you think of the 2nd Amendment?" ,
  "What's the most beautiful thing you have ever seen?" ,
  "How do you relax?" ,
  "How would your opinion on eating meat change if you were responsible for killing the animal?" ,
];
